//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATS.Core.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro é obrigatório..
        /// </summary>
        public static string BairroObrigatorio {
            get {
                return ResourceManager.GetString("BairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo deve conter no máximo {1} caracteres..
        /// </summary>
        public static string CampoComMaximoDeCaracteresPermitidoVM {
            get {
                return ResourceManager.GetString("CampoComMaximoDeCaracteresPermitidoVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo deve conter no mínimo {1} caracteres..
        /// </summary>
        public static string CampoComMinimoDeCaracteresPermitidoVM {
            get {
                return ResourceManager.GetString("CampoComMinimoDeCaracteresPermitidoVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo é obrigatório..
        /// </summary>
        public static string CargoObrigatorio {
            get {
                return ResourceManager.GetString("CargoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é inválido..
        /// </summary>
        public static string CEPInvalido {
            get {
                return ResourceManager.GetString("CEPInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é obrigatório..
        /// </summary>
        public static string CepObrigatorio {
            get {
                return ResourceManager.GetString("CepObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP em tamanho incorreto..
        /// </summary>
        public static string CepTamanhoInvalido {
            get {
                return ResourceManager.GetString("CepTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatório..
        /// </summary>
        public static string CidadeObrigatorio {
            get {
                return ResourceManager.GetString("CidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string CNPJInvalido {
            get {
                return ResourceManager.GetString("CNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ já cadastrado para outra empresa..
        /// </summary>
        public static string CNPJJaExiste {
            get {
                return ResourceManager.GetString("CNPJJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ é obrigatório..
        /// </summary>
        public static string CNPJObrigatorio {
            get {
                return ResourceManager.GetString("CNPJObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ em tamanho incorreto..
        /// </summary>
        public static string CNPJTamanhoInvalido {
            get {
                return ResourceManager.GetString("CNPJTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado para outra pessoa..
        /// </summary>
        public static string CPFJaExiste {
            get {
                return ResourceManager.GetString("CPFJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório..
        /// </summary>
        public static string CPFObrigatorio {
            get {
                return ResourceManager.GetString("CPFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF em tamanho incorreto..
        /// </summary>
        public static string CPFTamanhoInvalido {
            get {
                return ResourceManager.GetString("CPFTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CTPS é obrigatório..
        /// </summary>
        public static string CTPSObrigatorio {
            get {
                return ResourceManager.GetString("CTPSObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Admissão é obrigatorio..
        /// </summary>
        public static string DataDeAdmissaoObrigatorio {
            get {
                return ResourceManager.GetString("DataDeAdmissaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválido..
        /// </summary>
        public static string DataDeNascimentoInvalido {
            get {
                return ResourceManager.GetString("DataDeNascimentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento é obrigatório..
        /// </summary>
        public static string DataDeNascimentoObrigatorio {
            get {
                return ResourceManager.GetString("DataDeNascimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição é obrigatório..
        /// </summary>
        public static string DescricaoObrigatorio {
            get {
                return ResourceManager.GetString("DescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição em tamanho incorreto..
        /// </summary>
        public static string DescricaoTamanhoInvalido {
            get {
                return ResourceManager.GetString("DescricaoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail em tamanho incorreto..
        /// </summary>
        public static string EmailTamanhoIncorreto {
            get {
                return ResourceManager.GetString("EmailTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço é obrigatório..
        /// </summary>
        public static string EnderecoObrigatorio {
            get {
                return ResourceManager.GetString("EnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é inválido..
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O funcionário é obrigatório..
        /// </summary>
        public static string FuncionarioObrigatorio {
            get {
                return ResourceManager.GetString("FuncionarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O horário de entrada é obrigatório..
        /// </summary>
        public static string HorarioDeEntradaObrigatorio {
            get {
                return ResourceManager.GetString("HorarioDeEntradaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O horário de saída é obrigatório..
        /// </summary>
        public static string HorarioDeSaidaObrigatorio {
            get {
                return ResourceManager.GetString("HorarioDeSaidaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A inscrição é obrigatório..
        /// </summary>
        public static string InscricaoObrigatorio {
            get {
                return ResourceManager.GetString("InscricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição está no tamanho incorreto..
        /// </summary>
        public static string InscricaoTamanhoInvalido {
            get {
                return ResourceManager.GetString("InscricaoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Produto é obrigatório..
        /// </summary>
        public static string ItemProdutoObrigatorio {
            get {
                return ResourceManager.GetString("ItemProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro é obrigatório..
        /// </summary>
        public static string LogradouroObrigatorio {
            get {
                return ResourceManager.GetString("LogradouroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome fantasia é obrigatório..
        /// </summary>
        public static string NomeFantasiaObrigatorio {
            get {
                return ResourceManager.GetString("NomeFantasiaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Fantasia está no tamanho incorreto..
        /// </summary>
        public static string NomeFantasiaTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeFantasiaTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome em tamanho incorreto..
        /// </summary>
        public static string NomeTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório..
        /// </summary>
        public static string NumeroObrigatorio {
            get {
                return ResourceManager.GetString("NumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Física é obrigatório..
        /// </summary>
        public static string PessoaFisicaObrigatorio {
            get {
                return ResourceManager.GetString("PessoaFisicaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Jurídica é obrigatório..
        /// </summary>
        public static string PessoaJuridicaObrigatorio {
            get {
                return ResourceManager.GetString("PessoaJuridicaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa é obrigatório..
        /// </summary>
        public static string PessoaObrigatorio {
            get {
                return ResourceManager.GetString("PessoaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A razão social é obrigatória..
        /// </summary>
        public static string RazaoSocialObrigatorio {
            get {
                return ResourceManager.GetString("RazaoSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social está no tamanho incorreto..
        /// </summary>
        public static string RazaoSocialTamanhoInvalido {
            get {
                return ResourceManager.GetString("RazaoSocialTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rede social é obrigatória..
        /// </summary>
        public static string RedeSocialObrigatorio {
            get {
                return ResourceManager.GetString("RedeSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG já cadastrado para outra pessoa..
        /// </summary>
        public static string RGJaExiste {
            get {
                return ResourceManager.GetString("RGJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O site é obrigatório..
        /// </summary>
        public static string SiteObrigatorio {
            get {
                return ResourceManager.GetString("SiteObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do sócio principal é obrigatório..
        /// </summary>
        public static string SocioInvalido {
            get {
                return ResourceManager.GetString("SocioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sócio está no tamanho incorreto..
        /// </summary>
        public static string SocioTamanhoInvalido {
            get {
                return ResourceManager.GetString("SocioTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente números..
        /// </summary>
        public static string SomenteNumeros {
            get {
                return ResourceManager.GetString("SomenteNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status é obrigatório..
        /// </summary>
        public static string StatusObrigatorio {
            get {
                return ResourceManager.GetString("StatusObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da Agenda está no tamanho incorreto..
        /// </summary>
        public static string StatusTamanhoInvalido {
            get {
                return ResourceManager.GetString("StatusTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho é obrigatório..
        /// </summary>
        public static string TamanhoObrigatorio {
            get {
                return ResourceManager.GetString("TamanhoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone inválido..
        /// </summary>
        public static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório..
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone em tamanho incorreto..
        /// </summary>
        public static string TelefoneTamanhoIncorreto {
            get {
                return ResourceManager.GetString("TelefoneTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da Agenda é obrigatório..
        /// </summary>
        public static string TituloDaAgendaObrigatorio {
            get {
                return ResourceManager.GetString("TituloDaAgendaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da Agenda está no tamanho incorreto..
        /// </summary>
        public static string TituloDaAgendaTamanhoInvalido {
            get {
                return ResourceManager.GetString("TituloDaAgendaTamanhoInvalido", resourceCulture);
            }
        }
    }
}
