//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATS.Core.Domain.Resources.Texto", typeof(Texto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associado com sucesso..
        /// </summary>
        public static string AssociadoComSucesso {
            get {
                return ResourceManager.GetString("AssociadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro atualizado com sucesso..
        /// </summary>
        public static string AtualizadoComSucesso {
            get {
                return ResourceManager.GetString("AtualizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado com sucesso..
        /// </summary>
        public static string CadastroComSucesso {
            get {
                return ResourceManager.GetString("CadastroComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado com sucesso..
        /// </summary>
        public static string CanceladoComSucesso {
            get {
                return ResourceManager.GetString("CanceladoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim obrigatório quando a situação for de Atendimento Finalizado..
        /// </summary>
        public static string DataFinalObrigatorioParaStatusAtendimentoFinalizado {
            get {
                return ResourceManager.GetString("DataFinalObrigatorioParaStatusAtendimentoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desassociado com sucesso..
        /// </summary>
        public static string DesassociadoComSucesso {
            get {
                return ResourceManager.GetString("DesassociadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma opção.
        /// </summary>
        public static string EscolhaOpcao {
            get {
                return ResourceManager.GetString("EscolhaOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluído com sucesso..
        /// </summary>
        public static string ExcluidoComSucesso {
            get {
                return ResourceManager.GetString("ExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos. Verifique-os novamente..
        /// </summary>
        public static string ModeloVindoDaViewInvalida {
            get {
                return ResourceManager.GetString("ModeloVindoDaViewInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir permanentemente?.
        /// </summary>
        public static string MsgPopOverExclusao {
            get {
                return ResourceManager.GetString("MsgPopOverExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem registros..
        /// </summary>
        public static string NadaEncontrado {
            get {
                return ResourceManager.GetString("NadaEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível associar este item: {0}.
        /// </summary>
        public static string NaoEhPossivelAssociar {
            get {
                return ResourceManager.GetString("NaoEhPossivelAssociar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível desassociar este item: {0}.
        /// </summary>
        public static string NaoEhPossivelDesassociar {
            get {
                return ResourceManager.GetString("NaoEhPossivelDesassociar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir este item: {0}.
        /// </summary>
        public static string NaoEhPossivelExcluir {
            get {
                return ResourceManager.GetString("NaoEhPossivelExcluir", resourceCulture);
            }
        }
    }
}
